import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Themeprovider } from "@/components/Themeprovider";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
     
        <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Themeprovider attribute="class" defaultTheme='system' enableSystem disableTransitionOnChange>
            <div className="w-full">
              <Navbar />
             <div className="px-4 mt-10">{children}</div> 
            </div>
            
          </Themeprovider>
          
        </body>
        
     
      
    </html>
  );
}
